version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.24.4
    - 5.29.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.3
  - dependency-name: "@types/node"
    versions:
    - 14.14.25
    - 14.14.32
    - 14.14.37
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: next
    versions:
    - 10.0.6
    - 10.0.7
    - 10.0.8
  - dependency-name: "@next/bundle-analyzer"
    versions:
    - 10.0.8
  - dependency-name: postcss
    versions:
    - 8.2.7
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.1
  - dependency-name: sitemap
    versions:
    - 6.3.6
  - dependency-name: tailwindcss
    versions:
    - 2.0.3
